// The user's prompt corpus: every prompt they typed into any harness, cleaned
// of Prevail's own traffic, deduplicated, and keyed to the project it was
// about. This is the durable asset the Projects feature is built on: models
// change, the prompts (with their corrections and follow-ups) are what carry
// the intent.
//
// NEVER LOSE A RAW PROMPT (Fru, 2026-09-25). This module only reads. The
// capture streams and ledgers are append-only and nothing here filters them at
// write time: a misjudged filter at capture would delete a real prompt for
// good, while a misjudged filter here only hides it from one derived view.
// Every record keeps its exact original text (`raw`) whenever the text shown
// differs from it.
//
// Sources:
//   build/_meta/prompts/*.jsonl                    capture streams (every harness, every host)
//   data/domains/<d>/.system/journal.jsonl         Prevail's native ledger (kind:"intent")
import { closeSync, existsSync, openSync, readdirSync, readSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { runtimePath } from "./path-safety.ts";
import { vreadFile } from "./vault-session.ts";

export interface PromptRec {
  ts: number; // epoch ms
  tool: string; // claude | codex | prevail | opencode | antigravity | ...
  host: string;
  session: string;
  cwd: string;
  domain: string; // life domain for native-ledger prompts, else ""
  text: string; // what the user typed, preamble stripped
  raw?: string; // the exact captured text, set only when it differs from `text`
  src: string; // vault-relative file the record came from
  project: string; // deterministic project key (see projectKeyOf), "" when unknown
}

// Prompts Prevail (or a harness) wrote, not the user. Matched on how they
// start, after the ideal-state preamble is peeled off. Each of these was found
// in the live capture streams, most by the thousand: benchmark scoring and
// benchmark questions, the council, the distillers, harness notices.
const INTERNAL_STARTS = [
  // Prevail's entity tagger and its app sync-recipe designer (entities.ts,
  // apps-mirror.ts), seen in the streams when a run missed PREVAIL_INTERNAL.
  "Extract the specific named entities a person mentions",
  "You design a data sync recipe for the",
  "You are scoring a model's answer",
  "You are the chair of an AI council",
  "You are Prevail's",
  "You are a self-learning assistant",
  "You are a proactive task-planning AI",
  "(This is a general advisory question",
  "Context: <FILL IN",
  "[SYSTEM NOTIFICATION",
  "<system-reminder>",
  "<task-notification>",
  "<command-",
  "<local-command",
  "<context source=",
  "Stop hook feedback:",
  "The coordinator sent a message",
  "## Adversarial Claim Verifier",
  "This session is being continued from a previous conversation",
  "Caveat: The messages below were generated by the user while running local commands",
  "[Request interrupted by user",
  // Prevail's own Projects and Intent jobs, when the model CLI they run
  // through records them as if the user had typed them.
  "Classify each project one person worked on with AI tools",
  "Below are groups of messages one person typed to AI tools",
  "Below is what one person worked on with AI tools, week by week",
  "Write a short weekly letter to one person about their week with AI tools",
  "You are organizing one person's prompt history into PROJECTS",
  "Below are work sessions from one person's prompt history",
  "You are writing a REPLAY BRIEF for the project",
  "Below is everything one person has been working on, distilled from their full prompt history",
  "You are checking an existing codebase against the requirements for",
];
const CORPUS_PART = /^You are reading part \d+ of \d+ of the complete prompt history/;

const IDEAL_PREAMBLE = /^# (THE USER'S IDEAL STATE|WHO YOU'RE HELPING)/;

// A cwd inside a demo vault means the prompt came from Prevail's benchmark or
// demo persona ("Alex", a senior engineer weighing a Staff promotion), not the
// user. Those prompts leaked into chat context as if they were the user's own
// situation.
const DEMO_CWD = /(^|\/)(\.prevail\/demo-vault|vault-\d+-demo|demo-vault)(\/|$)/;

// Benchmark questions are "Context:\n<persona facts>\n\n<question>" and were
// captured when an Arena run spawned a CLI inside the real vault.
const BENCH_CONTEXT = /^Context:\s*\n?(Alex|Jordan|Household|Two-income|Austin|Senior SWE|Primary home|Assets:|Texas resident|Phoenix condo|No 529|Already maxing|Current TC|Family holiday)/;

// Per-domain review passes: "You are an expert <domain> coach reviewing this
// person's ...".
const COACH_REVIEW = /^You are an expert [\w-]+ coach reviewing this person/;

// Harness housekeeping typed at the prompt (/rename, /logout, /clear ...): no
// intent in them. A slash command WITH text after it ("/goal ship the site")
// is kept.
const HARNESS_COMMAND = /^\/(rename|logout|login|clear|compact|remote-control|exit|quit|model|resume|config|status|help|cost|init|mcp|permissions|doctor|memory|agents|hooks|ide|vim|theme|fast|effort|usage|context|add-dir|export|release-notes|upgrade|terminal-setup|privacy-settings|feedback|bug)\b\S*\s*\S{0,20}$/;

// Prompts another program or agent wrote into a harness: orchestrator
// payloads, briefs one agent hands another, health probes, pipeline scripts.
// Real work, but not the user's own words. Used when the session's entrypoint
// is unknown (records captured before it was recorded, and older than the
// local transcripts).
const AGENT_WRITTEN = [
  /^Context:\s*<FILL IN/,
  /^(Reply|Respond|Answer) with (just|exactly|only|the single word)/i,
  /^respond with just/i,
  /^-\s*You are agent [0-9a-f-]{8,}/,
  /^-\s*## Paperclip /,
  /^Work in (\/|[\w.-]+: \/private\/tmp\/)/,
  /^Site folder: \//,
  /^(Repo|Folder): (\/|~)/,
  /^Read-only investigation/,
  /^You are (a|an|the) [\w\s.,'-]{0,60}?(agent|operator|engine|chair|sub-agent|narration|writer|reviewer|judge)\b/i,
  /^(Current date \d{4}-\d{2}-\d{2}\. Advise|As of \w+ \d{1,2}, \d{4}, (advise|assess))/,
  /^## Source Extractor/,
  /^Another Claude session sent a message/,
  /^A session-scoped Stop hook is now active/,
  /^Read (and follow )?(the brief at )?\/private\/tmp\//,
  /^Read and follow \/private\/tmp\//,
  // The engine's preambles for non-Claude CLIs; the dash is an em dash in the
  // real text, so match either.
  /^# FILESYSTEM SCOPE [-\u2014] VAULT LOCK IS ON/,
  /^# DOMAIN IDEAL STATE/,
  /^You are (preparing a weekly briefing|the steward of the|helping build a personal canonical benchmark|seeding a chat|an expert YouTube thumbnail)/,
  /^You maintain three derived artifacts/,
  /^Write (the spoken )?narration for/,
  // Briefs an orchestrating agent hands a sub-agent: long, second person, and
  // about a job ("You are researching...", "You are the fact-checker for...").
  /^You are (?:[a-z]+ing|a|an|the)\b[\s\S]{380,}/,
  /^PARTNUM=\d+\./,
  // Prevail's own domain agents and preambles, sent through other CLIs.
  /^# [\w &]+ Agent\s*\n+## (Role|\d+\.)/,
  /^(\(This is a general advisory question[^)]*\)\s*)?# OUTPUT STYLE \(HARD RULE\)/,
  // A scheduled loop re-sending its instructions on a timer.
  /^AUTONOMOUS [\w-]+ (overnight )?loop\b/i,
  /^# Autonomous loop (tick|check)\b/,
  /^[\w.-]+ continuous work check-in\./,
  /^Goal check-in: \u00ab/,
  // Research sub-agents: their briefs, and a synthesis handed back in.
  /^Read-only (architecture )?(survey|research|audit)\b/i,
  /^## Synthesis: research report/,
  /^(Build a cited fact sheet|Deep-history fact research) for\b/,
];

// Some harnesses store the prompt JSON-quoted; judge the text inside.
const unquote = (text: string) => text.trimStart().replace(/^["'`]+/, "");

// Prevail's benchmark and council persona ("Alex Rivera", a Senior SWE in
// Austin at TechFlow going for Staff, partner Jordan, daughter Maya). Council
// runs through opencode carried these facts with no folder or signature, and
// a distiller that reads them thinks they are the user's own life.
const DEMO_PERSONA = /\b(Alex Rivera|TechFlow)\b|\bAlex\b[^\n]{0,120}\b(Senior SWE|Staff promo|Austin|Jordan|Maya)\b|\bSenior (SWE|software engineer)\b[^\n]{0,80}\bAustin\b|\bAustin\b[^\n]{0,80}\bSenior (SWE|software engineer)\b/i;

export function isAgentWritten(text: string): boolean {
  const t = unquote(text);
  return AGENT_WRITTEN.some((re) => re.test(t)) || DEMO_PERSONA.test(t.slice(0, 1500));
}

const HARNESS_NOTICE = /^(\[Image: original \d+x\d+, displayed at \d+x\d+\.[^\]]*\]|<task-notification\b[\s\S]*)$/;

export function isInternalPrompt(text: string, cwd = ""): boolean {
  const t = unquote(text);
  if (!t) return true;
  if (cwd && DEMO_CWD.test(cwd)) return true;
  if (BENCH_CONTEXT.test(t) || COACH_REVIEW.test(t) || HARNESS_COMMAND.test(t.trimEnd())) return true;
  if (CORPUS_PART.test(t)) return true;
  // Harness notices written into the transcript as if the user sent them.
  if (HARNESS_NOTICE.test(t.trim())) return true;
  return INTERNAL_STARTS.some((s) => t.startsWith(s));
}

// Desktop chats reach a CLI wrapped in context blocks (ideal state, profile,
// memory, prior turns). Recover what the user actually typed; null when the
// wrapped prompt is one of Prevail's own jobs.
export function userTextOf(raw: string, cwd = ""): string | null {
  let t = raw.trim();
  if (!t) return null;
  if (IDEAL_PREAMBLE.test(t)) {
    const next = t.lastIndexOf("User's next message: ");
    if (next >= 0) {
      t = t.slice(next + "User's next message: ".length).trim();
    } else {
      // Peel the ideal-state block; if a Prevail job prompt follows, drop it.
      const sep = t.indexOf("\n---\n");
      const rest = sep >= 0 ? t.slice(sep + 5).trim() : "";
      if (!rest || isInternalPrompt(rest)) return null;
      // Context blocks are "# HEADER" or "--- label ---" paragraphs; the user's
      // message is the trailing paragraph run after the last of them.
      const paras = rest.split(/\n{2,}/);
      let i = paras.length;
      while (i > 0 && !/^(#|---)/.test(paras[i - 1].trim())) i--;
      t = paras.slice(i).join("\n\n").trim();
      if (!t) return null;
    }
  }
  if (isInternalPrompt(t, cwd)) return null;
  return t;
}

// Where a prompt was typed says what it was about. Folders are normalized to a
// project root so every worktree, branch and subfolder of one repo lands on
// one key. Machine-specific roots come from `roots` (the vault's projects config):
//   <code dir>/<ns>/<ns>-<name>/src           -> <ns>-<name>   (namespaced project folders)
//   ~/.workmux/<repo>/<branch>                 -> <repo>
//   .../data/domains/<domain>/...              -> domain:<domain>
//   a folder whose name ends in "vault"        -> vault
export function projectKeyOf(cwd: string, home = homedir(), roots: string[] = []): string {
  if (!cwd) return "";
  let p = cwd.replace(/\/+$/, "");
  if (home && p.startsWith(home)) p = "~" + p.slice(home.length);
  p = p.replace(/^\/Users\/[^/]+/, "~");
  if (p === "~" || p === "/" || p === "") return "";
  if (/^(\/private)?\/(tmp|var)\//.test(p) || p.startsWith("~/Downloads")) return "";
  const dom = p.match(/\/data\/domains\/([^/]+)/);
  if (dom) return `domain:${dom[1].toLowerCase()}`;
  const segsAll = p.split("/").filter(Boolean);
  if (/vault$/i.test(segsAll[segsAll.length - 1] ?? "")) return "vault";
  const wm = p.match(/^~\/\.workmux\/([^/]+)/);
  if (wm) return wm[1].toLowerCase();
  const code = p.match(/^~\/(?:Documents|Projects|code|src|dev)\/(.+)$/);
  if (code) {
    const segs = code[1].split("/").filter(Boolean).map((x) => x.toLowerCase());
    // A namespaced child (web-apps/web-apps-shop) names the project.
    for (let i = 0; i + 1 < segs.length; i++) if (segs[i + 1].startsWith(`${segs[i]}-`)) return segs[i + 1];
    // Inside a monorepo root the user named, the next folder is the project.
    if (roots.includes(segs[0]) && segs[1]) return segs[1];
    return segs[0];
  }
  const dot = p.match(/^~\/\.([^/]+)/);
  if (dot) return `config:${dot[1].toLowerCase()}`;
  return (segsAll[segsAll.length - 1] ?? "").toLowerCase();
}

// Per-user corpus settings, kept in the vault (never in shipped code):
// <vault>/build/_meta/projects/config.json  {"roots": ["<monorepo folder>"]}
export function readCorpusConfig(vault: string): { roots: string[] } {
  try {
    const c = JSON.parse(vreadFile(runtimePath(vault, join("_meta", "projects", "config.json")))) as { roots?: unknown };
    return { roots: Array.isArray(c.roots) ? c.roots.filter((x): x is string => typeof x === "string").map((x) => x.toLowerCase()) : [] };
  } catch { return { roots: [] }; }
}

function readJsonl(path: string): Record<string, unknown>[] {
  let raw = "";
  try { raw = vreadFile(path); } catch { return []; }
  const out: Record<string, unknown>[] = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try { out.push(JSON.parse(line) as Record<string, unknown>); } catch { /* skip a torn line */ }
  }
  return out;
}

const str = (v: unknown): string => (typeof v === "string" ? v : "");

function domainsRoot(vault: string): string {
  const v4 = join(vault, "data", "domains");
  return existsSync(v4) ? v4 : vault;
}

export interface CorpusStats {
  records: number;
  internal: number; // Prevail's own model calls and harness notices
  program: number; // written by another program or agent, not typed by the user
  duplicates: number;
  kept: number;
}

// Claude Code sessions on this machine, by id, with how they were started:
// "cli" (a person at the prompt) or "sdk-cli" (headless, launched by a program
// or agent). Only the head of each transcript is read. Covers the transcripts
// still on disk, which Claude Code keeps for about a month.
const entryCache = new Map<string, Map<string, string>>();

export function claudeSessionEntries(home = homedir()): Map<string, string> {
  // Thousands of transcripts: scan once per process (a build and a timeline
  // in the same run share it).
  const cached = entryCache.get(home);
  if (cached) return cached;
  const out = new Map<string, string>();
  entryCache.set(home, out);
  const root = join(home, ".claude", "projects");
  let dirs: string[] = [];
  try { dirs = readdirSync(root); } catch { return out; }
  const buf = Buffer.alloc(16384);
  for (const d of dirs) {
    let files: string[] = [];
    try { files = readdirSync(join(root, d)).filter((f) => f.endsWith(".jsonl")); } catch { continue; }
    for (const f of files) {
      let fd = -1;
      try {
        fd = openSync(join(root, d, f), "r");
        const n = readSync(fd, buf, 0, buf.length, 0);
        for (const line of buf.subarray(0, n).toString("utf8").split("\n")) {
          const e = line.match(/"entrypoint":"([^"]+)"/);
          const sid = line.match(/"sessionId":"([^"]+)"/);
          if (e && sid) { out.set(sid[1], e[1]); break; }
        }
      } catch { /* unreadable transcript */ } finally { if (fd >= 0) closeSync(fd); }
    }
  }
  return out;
}

// Briefs one agent handed a sub-agent. Claude Code keeps each sub-agent's
// transcript under <session>/subagents/, its first "user" message being the
// brief. Records synced before sync marked them ("sidechain") are recognized
// here by session and opening text, for the transcripts still on disk.
const sidechainCache = new Map<string, Set<string>>();
export const sidechainKey = (session: string, text: string) => `${session}\u0001${text.trim().slice(0, 200)}`;

export function claudeSidechainBriefs(home = homedir()): Set<string> {
  const cached = sidechainCache.get(home);
  if (cached) return cached;
  const out = new Set<string>();
  sidechainCache.set(home, out);
  const root = join(home, ".claude", "projects");
  let dirs: string[] = [];
  try { dirs = readdirSync(root); } catch { return out; }
  const buf = Buffer.alloc(8192);
  for (const d of dirs) {
    let sessions: string[] = [];
    try { sessions = readdirSync(join(root, d), { withFileTypes: true }).filter((x) => x.isDirectory()).map((x) => x.name); } catch { continue; }
    for (const s of sessions) {
      let files: string[] = [];
      try { files = readdirSync(join(root, d, s, "subagents")).filter((f) => f.endsWith(".jsonl")); } catch { continue; }
      for (const f of files) {
        let fd = -1;
        try {
          fd = openSync(join(root, d, s, "subagents", f), "r");
          const n = readSync(fd, buf, 0, buf.length, 0);
          const head = buf.subarray(0, n).toString("utf8");
          const sid = head.match(/"sessionId":"([^"]+)"/)?.[1] ?? s;
          // The brief's opening, decoded from the JSON string (it may be cut
          // off by the head buffer, so no full JSON parse).
          const m = head.match(/"content":"((?:[^"\\]|\\.){1,1200})/);
          if (!m) continue;
          let text = "";
          try { text = JSON.parse(`"${m[1].replace(/\\$/, "")}"`); } catch { continue; }
          if (text.trim()) out.add(sidechainKey(sid, text));
        } catch { /* unreadable transcript */ } finally { if (fd >= 0) closeSync(fd); }
      }
    }
  }
  return out;
}

// Every user prompt, oldest first. A prompt typed twice in the same session
// (hook push + transcript sync) is one prompt; the same text in different
// sessions is kept, since repeating an instruction is itself a signal.
export function loadCorpus(vault: string, home: string = homedir()): { prompts: PromptRec[]; stats: CorpusStats } {
  const stats: CorpusStats = { records: 0, internal: 0, program: 0, duplicates: 0, kept: 0 };
  const entries = claudeSessionEntries(home);
  const briefs = claudeSidechainBriefs(home);
  const { roots } = readCorpusConfig(vault);
  const seen = new Set<string>();
  const prompts: PromptRec[] = [];
  const add = (r: Omit<PromptRec, "project" | "text" | "raw">, raw: string, entry = "") => {
    // opencode records Prevail's own runs with the prompt as one JSON-quoted
    // argument; none of the quoted ones in the live streams was typed.
    if (r.tool === "opencode" && /^\s*"[\s\S]*"\s*$/.test(raw)) { stats.records++; stats.program++; return; }
    stats.records++;
    const text = userTextOf(raw, r.cwd);
    if (!text) { stats.internal++; return; }
    const how = entry || (r.tool === "claude" ? entries.get(r.session) ?? "" : "");
    if (how === "sdk-cli" || how === "sidechain" || isAgentWritten(text)) { stats.program++; return; }
    if (r.tool === "claude" && briefs.has(sidechainKey(r.session, text))) { stats.program++; return; }
    const key = `${r.tool}\u0001${r.session}\u0001${text}`;
    if (seen.has(key)) { stats.duplicates++; return; }
    seen.add(key);
    prompts.push({ ...r, text, ...(text !== raw ? { raw } : {}), project: r.domain ? `domain:${r.domain}` : projectKeyOf(r.cwd, home, roots) });
  };

  const dir = runtimePath(vault, join("_meta", "prompts"));
  let files: string[] = [];
  try { files = readdirSync(dir).filter((f) => f.endsWith(".jsonl")); } catch { /* no captures yet */ }
  for (const f of files.sort()) {
    for (const r of readJsonl(join(dir, f))) {
      const ts = typeof r.epoch_ms === "number" ? r.epoch_ms : Date.parse(str(r.ts)) || 0;
      add({ ts, tool: str(r.tool) || f.split(".")[0], host: str(r.host), session: str(r.session), cwd: str(r.cwd), domain: "", src: `build/_meta/prompts/${f}` }, str(r.prompt), str(r.entry));
    }
  }

  const droot = domainsRoot(vault);
  let domains: string[] = [];
  try { domains = readdirSync(droot, { withFileTypes: true }).filter((d) => d.isDirectory() && !d.name.startsWith(".") && !d.name.startsWith("_")).map((d) => d.name); } catch { /* */ }
  for (const d of domains) {
    // The live ledger plus its archive: the learn daemon rotates consumed
    // lines into *.archive.jsonl, and those are prompts too.
    for (const rel of [".system/journal.archive.jsonl", ".system/journal.jsonl", "_intents.archive.jsonl", "_intents.jsonl"]) {
      const p = join(droot, d, rel);
      if (!existsSync(p)) continue;
      const src = p.startsWith(vault) ? p.slice(vault.length + 1) : p;
      for (const r of readJsonl(p)) {
        if (r.kind !== "intent") continue;
        const ts = typeof r.ts === "number" ? (r.ts < 1e12 ? r.ts * 1000 : r.ts) : Date.parse(str(r.ts)) || 0;
        add({ ts, tool: "prevail", host: str(r.host), session: str(r.session) || str(r.thread), cwd: "", domain: d.toLowerCase(), src }, str(r.message) || str(r.prompt));
      }
    }
  }

  // A session is one piece of work: a prompt with no folder signal (typed at
  // "/" or a temp dir) takes the project its session settled on.
  const bySession = new Map<string, Map<string, number>>();
  for (const p of prompts) {
    if (!p.project || !p.session) continue;
    const m = bySession.get(p.session) ?? new Map<string, number>();
    m.set(p.project, (m.get(p.project) ?? 0) + 1);
    bySession.set(p.session, m);
  }
  for (const p of prompts) {
    if (p.project || !p.session) continue;
    const m = bySession.get(p.session);
    if (!m) continue;
    p.project = [...m.entries()].sort((a, b) => b[1] - a[1])[0][0];
  }

  prompts.sort((a, b) => a.ts - b.ts);
  stats.kept = prompts.length;
  return { prompts, stats };
}

export function monthOf(ts: number): string {
  const d = new Date(ts);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}
