// The user's prompt corpus: every prompt they typed into any harness, cleaned
// of Prevail's own traffic, deduplicated, and keyed to the project it was
// about. This is the durable asset the Projects feature is built on: models
// change, the prompts (with their corrections and follow-ups) are what carry
// the intent.
//
// NEVER LOSE A RAW PROMPT (Fru, 2026-09-25). This module only reads. The
// capture streams and ledgers are append-only and nothing here filters them at
// write time: a misjudged filter at capture would delete a real prompt for
// good, while a misjudged filter here only hides it from one derived view.
// Every record keeps its exact original text (`raw`) whenever the text shown
// differs from it.
//
// Sources:
//   build/_meta/prompts/*.jsonl                    capture streams (every harness, every host)
//   data/domains/<d>/.system/journal.jsonl         Prevail's native ledger (kind:"intent")
import { closeSync, existsSync, openSync, readdirSync, readSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { runtimePath } from "./path-safety.ts";
import { vreadFile } from "./vault-session.ts";

export interface PromptRec {
  ts: number; // epoch ms
  tool: string; // claude | codex | prevail | opencode | antigravity | ...
  host: string;
  session: string;
  cwd: string;
  domain: string; // life domain for native-ledger prompts, else ""
  text: string; // what the user typed, preamble stripped
  raw?: string; // the exact captured text, set only when it differs from `text`
  src: string; // vault-relative file the record came from
  project: string; // deterministic project key (see projectKeyOf), "" when unknown
}

// Prompts Prevail (or a harness) wrote, not the user. Matched on how they
// start, after the ideal-state preamble is peeled off. Each of these was found
// in the live capture streams, most by the thousand: benchmark scoring and
// benchmark questions, the council, the distillers, harness notices.
const INTERNAL_STARTS = [
  "You are scoring a model's answer",
  "You are the chair of an AI council",
  "You are Prevail's",
  "You are a self-learning assistant",
  "You are a proactive task-planning AI",
  "(This is a general advisory question",
  "Context: <FILL IN",
  "[SYSTEM NOTIFICATION",
  "<system-reminder>",
  "<task-notification>",
  "<command-",
  "<local-command",
  "<context source=",
  "Stop hook feedback:",
  "The coordinator sent a message",
  "## Adversarial Claim Verifier",
  "This session is being continued from a previous conversation",
  "Caveat: The messages below were generated by the user while running local commands",
  "[Request interrupted by user",
];

const IDEAL_PREAMBLE = /^# THE USER'S IDEAL STATE/;

// A cwd inside a demo vault means the prompt came from Prevail's benchmark or
// demo persona ("Alex", a senior engineer weighing a Staff promotion), not the
// user. Those prompts leaked into chat context as if they were the user's own
// situation.
const DEMO_CWD = /(^|\/)(\.prevail\/demo-vault|vault-\d+-demo|demo-vault)(\/|$)/;

// Benchmark questions are "Context:\n<persona facts>\n\n<question>" and were
// captured when an Arena run spawned a CLI inside the real vault.
const BENCH_CONTEXT = /^Context:\s*\n?(Alex|Jordan|Household|Two-income|Austin|Senior SWE|Primary home|Assets:|Texas resident|Phoenix condo|No 529|Already maxing|Current TC|Family holiday)/;

// Per-domain review passes: "You are an expert <domain> coach reviewing this
// person's ...".
const COACH_REVIEW = /^You are an expert [\w-]+ coach reviewing this person/;

// Harness housekeeping typed at the prompt (/rename, /logout, /clear ...): no
// intent in them. A slash command WITH text after it ("/goal ship the site")
// is kept.
const HARNESS_COMMAND = /^\/(rename|logout|login|clear|compact|remote-control|exit|quit|model|resume|config|status|help|cost|init|mcp|permissions|doctor|memory|agents|hooks|ide|vim|theme|fast|effort|usage|context|add-dir|export|release-notes|upgrade|terminal-setup|privacy-settings|feedback|bug)\b\S*\s*\S{0,20}$/;

// Prompts another program or agent wrote into a harness: orchestrator
// payloads, briefs one agent hands another, health probes, pipeline scripts.
// Real work, but not the user's own words. Used when the session's entrypoint
// is unknown (records captured before it was recorded, and older than the
// local transcripts).
const AGENT_WRITTEN = [
  /^Context:\s*<FILL IN/,
  /^(Reply|Respond|Answer) with (just|exactly|only|the single word)/i,
  /^respond with just/i,
  /^-\s*You are agent [0-9a-f-]{8,}/,
  /^-\s*## Paperclip /,
  /^Work in (\/|[\w.-]+: \/private\/tmp\/)/,
  /^Site folder: \//,
  /^(Repo|Folder): (\/|~)/,
  /^Read-only investigation/,
  /^You are (a|an|the) [\w\s.,'-]{0,60}?(agent|operator|engine|chair|sub-agent|narration|writer|reviewer|judge)\b/i,
  /^(Current date \d{4}-\d{2}-\d{2}\. Advise|As of \w+ \d{1,2}, \d{4}, (advise|assess))/,
  /^## Source Extractor/,
  /^Another Claude session sent a message/,
  /^A session-scoped Stop hook is now active/,
  /^Read (and follow )?(the brief at )?\/private\/tmp\//,
  /^Read and follow \/private\/tmp\//,
  /^# FILESYSTEM SCOPE - VAULT LOCK IS ON/,
  /^You are (preparing a weekly briefing|the steward of the|helping build a personal canonical benchmark|seeding a chat|an expert YouTube thumbnail)/,
  /^You maintain three derived artifacts/,
  /^Write (the spoken )?narration for/,
];

// Some harnesses store the prompt JSON-quoted; judge the text inside.
const unquote = (text: string) => text.trimStart().replace(/^["'`]+/, "");

export function isAgentWritten(text: string): boolean {
  const t = unquote(text);
  return AGENT_WRITTEN.some((re) => re.test(t));
}

export function isInternalPrompt(text: string, cwd = ""): boolean {
  const t = unquote(text);
  if (!t) return true;
  if (cwd && DEMO_CWD.test(cwd)) return true;
  if (BENCH_CONTEXT.test(t) || COACH_REVIEW.test(t) || HARNESS_COMMAND.test(t.trimEnd())) return true;
  return INTERNAL_STARTS.some((s) => t.startsWith(s));
}

// Desktop chats reach a CLI wrapped in context blocks (ideal state, profile,
// memory, prior turns). Recover what the user actually typed; null when the
// wrapped prompt is one of Prevail's own jobs.
export function userTextOf(raw: string, cwd = ""): string | null {
  let t = raw.trim();
  if (!t) return null;
  if (IDEAL_PREAMBLE.test(t)) {
    const next = t.lastIndexOf("User's next message: ");
    if (next >= 0) {
      t = t.slice(next + "User's next message: ".length).trim();
    } else {
      // Peel the ideal-state block; if a Prevail job prompt follows, drop it.
      const sep = t.indexOf("\n---\n");
      const rest = sep >= 0 ? t.slice(sep + 5).trim() : "";
      if (!rest || isInternalPrompt(rest)) return null;
      // Context blocks are "# HEADER" or "--- label ---" paragraphs; the user's
      // message is the trailing paragraph run after the last of them.
      const paras = rest.split(/\n{2,}/);
      let i = paras.length;
      while (i > 0 && !/^(#|---)/.test(paras[i - 1].trim())) i--;
      t = paras.slice(i).join("\n\n").trim();
      if (!t) return null;
    }
  }
  if (isInternalPrompt(t, cwd)) return null;
  return t;
}

// Where a prompt was typed says what it was about. Folders are normalized to a
// project root so every worktree, branch and subfolder of one repo lands on
// one key:
//   ~/Documents/fru/fd-apps/fd-apps-prevail-desktop/src-tauri  -> fd-apps-prevail-desktop
//   ~/.workmux/fd-apps-prevail-cli/entity-links                  -> fd-apps-prevail-cli
//   <vault>/data/domains/tax/...                                  -> domain:tax
export function projectKeyOf(cwd: string, home = homedir()): string {
  if (!cwd) return "";
  let p = cwd.replace(/\/+$/, "");
  if (home && p.startsWith(home)) p = "~" + p.slice(home.length);
  p = p.replace(/^\/Users\/[^/]+/, "~");
  if (p === "~" || p === "/" || p === "") return "";
  if (/^(\/private)?\/(tmp|var)\//.test(p) || p.startsWith("~/Downloads")) return "";
  const dom = p.match(/\/data\/domains\/([^/]+)/) ?? p.match(/(?:fru-vault|PrevailVault)\/([^/]+)/);
  if (dom && !["build", "data"].includes(dom[1])) return `domain:${dom[1].toLowerCase()}`;
  if (/(fru-vault|PrevailVault)$/.test(p)) return "vault";
  const wm = p.match(/^~\/\.workmux\/([^/]+)/);
  if (wm) return wm[1].toLowerCase();
  const fru = p.match(/^~\/Documents\/fru\/([^/]+)(?:\/([^/]+))?/);
  if (fru) {
    const [, ns, proj] = fru;
    // A namespaced project folder (fd-apps/fd-apps-memosa); a loose top-level
    // folder (vault/, docs) keys on itself.
    if (proj && /^(fd|fw)-/.test(ns)) return proj.toLowerCase();
    return ns.toLowerCase();
  }
  const docs = p.match(/^~\/(?:Documents|Projects|code|src|dev)\/([^/]+)/);
  if (docs) return docs[1].toLowerCase();
  const dot = p.match(/^~\/\.([^/]+)/);
  if (dot) return `config:${dot[1].toLowerCase()}`;
  const seg = p.split("/").filter(Boolean);
  return (seg[seg.length - 1] ?? "").toLowerCase();
}

function readJsonl(path: string): Record<string, unknown>[] {
  let raw = "";
  try { raw = vreadFile(path); } catch { return []; }
  const out: Record<string, unknown>[] = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try { out.push(JSON.parse(line) as Record<string, unknown>); } catch { /* skip a torn line */ }
  }
  return out;
}

const str = (v: unknown): string => (typeof v === "string" ? v : "");

function domainsRoot(vault: string): string {
  const v4 = join(vault, "data", "domains");
  return existsSync(v4) ? v4 : vault;
}

export interface CorpusStats {
  records: number;
  internal: number; // Prevail's own model calls and harness notices
  program: number; // written by another program or agent, not typed by the user
  duplicates: number;
  kept: number;
}

// Claude Code sessions on this machine, by id, with how they were started:
// "cli" (a person at the prompt) or "sdk-cli" (headless, launched by a program
// or agent). Only the head of each transcript is read. Covers the transcripts
// still on disk, which Claude Code keeps for about a month.
export function claudeSessionEntries(home = homedir()): Map<string, string> {
  const out = new Map<string, string>();
  const root = join(home, ".claude", "projects");
  let dirs: string[] = [];
  try { dirs = readdirSync(root); } catch { return out; }
  const buf = Buffer.alloc(16384);
  for (const d of dirs) {
    let files: string[] = [];
    try { files = readdirSync(join(root, d)).filter((f) => f.endsWith(".jsonl")); } catch { continue; }
    for (const f of files) {
      let fd = -1;
      try {
        fd = openSync(join(root, d, f), "r");
        const n = readSync(fd, buf, 0, buf.length, 0);
        for (const line of buf.subarray(0, n).toString("utf8").split("\n")) {
          const e = line.match(/"entrypoint":"([^"]+)"/);
          const sid = line.match(/"sessionId":"([^"]+)"/);
          if (e && sid) { out.set(sid[1], e[1]); break; }
        }
      } catch { /* unreadable transcript */ } finally { if (fd >= 0) closeSync(fd); }
    }
  }
  return out;
}

// Every user prompt, oldest first. A prompt typed twice in the same session
// (hook push + transcript sync) is one prompt; the same text in different
// sessions is kept, since repeating an instruction is itself a signal.
export function loadCorpus(vault: string, home = homedir()): { prompts: PromptRec[]; stats: CorpusStats } {
  const stats: CorpusStats = { records: 0, internal: 0, program: 0, duplicates: 0, kept: 0 };
  const entries = claudeSessionEntries(home);
  const seen = new Set<string>();
  const prompts: PromptRec[] = [];
  const add = (r: Omit<PromptRec, "project" | "text" | "raw">, raw: string, entry = "") => {
    stats.records++;
    const text = userTextOf(raw, r.cwd);
    if (!text) { stats.internal++; return; }
    const how = entry || (r.tool === "claude" ? entries.get(r.session) ?? "" : "");
    if (how === "sdk-cli" || isAgentWritten(text)) { stats.program++; return; }
    const key = `${r.tool}\u0001${r.session}\u0001${text}`;
    if (seen.has(key)) { stats.duplicates++; return; }
    seen.add(key);
    prompts.push({ ...r, text, ...(text !== raw ? { raw } : {}), project: r.domain ? `domain:${r.domain}` : projectKeyOf(r.cwd, home) });
  };

  const dir = runtimePath(vault, join("_meta", "prompts"));
  let files: string[] = [];
  try { files = readdirSync(dir).filter((f) => f.endsWith(".jsonl")); } catch { /* no captures yet */ }
  for (const f of files.sort()) {
    for (const r of readJsonl(join(dir, f))) {
      const ts = typeof r.epoch_ms === "number" ? r.epoch_ms : Date.parse(str(r.ts)) || 0;
      add({ ts, tool: str(r.tool) || f.split(".")[0], host: str(r.host), session: str(r.session), cwd: str(r.cwd), domain: "", src: `build/_meta/prompts/${f}` }, str(r.prompt), str(r.entry));
    }
  }

  const droot = domainsRoot(vault);
  let domains: string[] = [];
  try { domains = readdirSync(droot, { withFileTypes: true }).filter((d) => d.isDirectory() && !d.name.startsWith(".") && !d.name.startsWith("_")).map((d) => d.name); } catch { /* */ }
  for (const d of domains) {
    // The live ledger plus its archive: the learn daemon rotates consumed
    // lines into *.archive.jsonl, and those are prompts too.
    for (const rel of [".system/journal.archive.jsonl", ".system/journal.jsonl", "_intents.archive.jsonl", "_intents.jsonl"]) {
      const p = join(droot, d, rel);
      if (!existsSync(p)) continue;
      const src = p.startsWith(vault) ? p.slice(vault.length + 1) : p;
      for (const r of readJsonl(p)) {
        if (r.kind !== "intent") continue;
        const ts = typeof r.ts === "number" ? (r.ts < 1e12 ? r.ts * 1000 : r.ts) : Date.parse(str(r.ts)) || 0;
        add({ ts, tool: "prevail", host: str(r.host), session: str(r.session) || str(r.thread), cwd: "", domain: d.toLowerCase(), src }, str(r.message) || str(r.prompt));
      }
    }
  }

  // A session is one piece of work: a prompt with no folder signal (typed at
  // "/" or a temp dir) takes the project its session settled on.
  const bySession = new Map<string, Map<string, number>>();
  for (const p of prompts) {
    if (!p.project || !p.session) continue;
    const m = bySession.get(p.session) ?? new Map<string, number>();
    m.set(p.project, (m.get(p.project) ?? 0) + 1);
    bySession.set(p.session, m);
  }
  for (const p of prompts) {
    if (p.project || !p.session) continue;
    const m = bySession.get(p.session);
    if (!m) continue;
    p.project = [...m.entries()].sort((a, b) => b[1] - a[1])[0][0];
  }

  prompts.sort((a, b) => a.ts - b.ts);
  stats.kept = prompts.length;
  return { prompts, stats };
}

export function monthOf(ts: number): string {
  const d = new Date(ts);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}
